[workspace]
members = ["crates/core", "crates/cli", "src-tauri"]
resolver = "2"

[workspace.package]
version = "1.2.0"
license = "MIT"
authors = ["reekid420"]
repository = "https://github.com/reekid420/website-searcher"
edition = "2024"
rust-version = "1.89"
